### PR TITLE
Create object for installation directory

### PR DESCRIPTION
**Pull request by stefanoberri**
- Create a class to track the reference installation directory
- Change the `install` function to take an extra optional argument and use the new class to set the directory. This should not change the defualt behaviour

### CODE REVIEW

**Comment by stefanoberri** [comment]
Hi. Here a first PR where I made a very small change to get started. I have some comments and questions:

- I have tried to change the existing files as little as possible and add new files instead. Apologies for some space removal my editor has automatically performed.
- I have added a new `tests` folder with unit tests, as I am not very sure how you kick off the available tests at the moment. I am happy to move them somewhere else.
- I have noticed that the code uses tab rather than spaces for indentation. Coding style guides usually recommend spaces (https://peps.python.org/pep-0008/#tabs-or-spaces) let me know if this is a problem.
- We usually use Black (https://pypi.org/project/black/) for automatic formatting and we find it very useful to keep formatting a non issue, maybe you want to consider it for this project too.
- I have used `unittest` for the unit tests. We usually use `pytest` instead as it is more flexible and very well supported but adds a dependency burden. Let me know if you would be happy to adopt it.

**Comment by mdbarnesUCSD** [comment]
Thanks @stefanoberri for opening this pull request and for all of the comments and questions.

> Hi. Here a first PR where I made a very small change to get started. I have some comments and questions:
> 
> * I have tried to change the existing files as little as possible and add new files instead. Apologies for some space removal my editor has automatically performed.
> * I have added a new `tests` folder with unit tests, as I am not very sure how you kick off the available tests at the moment. I am happy to move them somewhere else.
* Currently the tests are minimal and is a [single script](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/.travis.yml#L22) run during the Travis CI/CD. The test [loads inputs from genome directories](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/tree/master/SigProfilerMatrixGenerator/references/tests) and [verifies output against corresponding matrices here](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/tree/master/SigProfilerMatrixGenerator/references/tests/solutions).  We will be looking into modifying the current script to use pytest.
> * I have noticed that the code uses tab rather than spaces for indentation. Coding style guides usually recommend spaces (https://peps.python.org/pep-0008/#tabs-or-spaces) let me know if this is a problem.
* We will use spaces moving forward and will make a single commit that modifies tabs to spaces.
> * We usually use Black (https://pypi.org/project/black/) for automatic formatting and we find it very useful to keep formatting a non issue, maybe you want to consider it for this project too.
* Took a look at Black, and will look to adopt soon.
> * I have used `unittest` for the unit tests. We usually use `pytest` instead as it is more flexible and very well supported but adds a dependency burden. Let me know if you would be happy to adopt it.
* Pytest would be great to use and will be looking to expand the current tests.

We are working to incorporate this update so that users can specify where to save/load the TSB files from.

**Comment by stefanoberri** [comment]
Thank you @mdbarnesUCSD very much for the reply. Very happy to contribute to this useful tool.

- For the code formatting, I have opened a new pull request to the `development` branch, where I **only** applied automatic formatting. See #136. 
- About pytest, I don't think you should change your current script running in CI/CD. After my initial comment, I figured out how to run that script locally, and it was useful to spot a couple of problems with my code. That is a useful end-to-end tests that could stay as is. I will change the **unit** tests to use pytest, but that is not urgent.
- From your comment, I understand you are waiting for the feature to be "complete" (add the volume option to all functions that require to specify the installation folder). I can do that, but from experience I know that it is less disruptive to produce small incremental and backward compatible changes rather than a big one. So I suggest that we review and incorporate code in small steps - particularly as I get to know the codebase and your process. However, if you prefer a "full" PR, I can also go down this route, but reviewing and debugging might become more challenging and time consuming.
- I am a bit puzzled why the test run for me locally, but not on the Travis CI/CD. Those builds should be very reproducible. Admittedly, mine are not exactly running on Ubuntu. If you have any insight, please let me know.
 
Looking forward to hearing from you

**Comment by mdbarnesUCSD** [comment]
Great, thanks for opening the pull request with the automatic formatting changes. We agree that incremental changes are better and are happy to move forward with this pull request. The CI/CD build was breaking because of the pandas 2.0.0 release. The development branch requires pandas<2.0.0, so this should resolve.

**Pull request merged**
